---
- name: Set the hostname
  hostname:
    name: "{{ COMMON_SERVER_HOSTNAME }}"

- name: Set system timezone to UTC
  template:
    src: timezone
    dest: /etc/timezone
    mode: 0644

- name: Set local timezone to UTC
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: true

- name: Configure hosts file
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0544

- name: Update all packages to their latest version
  apt:
    update_cache: true
    cache_valid_time: 3600
    name: "*"
    state: latest

- name: Install common dependencies
  apt:
    name:
      - ca-certificates
      - git
      - python3
      - python3-pip
      - vim
    state: present

- name: Install dependencies
  apt:
    name: "{{ COMMON_SERVER_DEPENDENCIES }}"
    state: present

- name: "Apply OS hardening"
  import_role:
    name: devsec.hardening.os_hardening
  vars:
    os_ignore_users: "{{ HARDENING_OS_IGNORE_USERS }}"
    os_remove_additional_root_users: "{{ HARDENING_OS_REMOVE_ADDITIONAL_ROOT_USERS }}"
    os_security_auto_logout: "{{ HARDENING_OS_SECURITY_AUTO_LOGOUT }}"
    sysctl_overwrite:
      net.ipv4.ip_forward: 1

- name: "Apply SSH hardening"
  import_role:
    name: devsec.hardening.ssh_hardening
  vars:
    ssh_print_motd: true
    ssh_print_pam_motd: true
    ssh_print_last_log: true
    ssh_allow_users: "{{ HARDENING_SSH_ALLOW_USERS }}"

- name: "Ensure SWAP files configured"
  import_role:
    name: geerlingguy.ansible-role-swap
  vars:
    swap_file_size_mb: "{{ COMMON_SWAP_FILE_SIZE_MB }}"
