---
collections:
  - name: devsec.hardening
    source: https://github.com/dev-sec/ansible-collection-hardening.git
    version: 9ebc603b6bcd36c25ede10f641a74b089644b6a7
    type: git

roles:
  - name: geerlingguy.ansible-role-swap
    src: https://github.com/geerlingguy/ansible-role-swap.git
    version: 97614edef651f6de44a2707a51ffca6e2a553cef
    scm: git

  - name: geerlingguy.ansible-role-certbot
    src: https://github.com/geerlingguy/ansible-role-certbot.git
    version: 3b3cc546d123c06b294182c747cacaab83174fca
    scm: git
