---
- name: Install python dependencies
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
    state: present

- name: Ensure update checker path exists
  file:
    path: "{{ UPDATE_CHECKER_PATH }}"
    state: directory

- name: Download update checker
  git:
    repo: "{{ UPDATE_CHECKER_REPO }}"
    dest: "{{ UPDATE_CHECKER_PATH }}"
    version: "{{ UPDATE_CHECKER_VERSION }}"

- name: Install requirements
  pip:
    virtualenv: "{{ UPDATE_CHECKER_PATH }}/venv"
    extra_args: --no-build-isolation
    requirements: "{{ UPDATE_CHECKER_PATH }}/requirements.txt"

- name: Start update checker
  shell:
    chdir: "{{ UPDATE_CHECKER_PATH }}"
    cmd: |
      ./venv/bin/python3 ./app/update_server.py >> ./logs/app.log 2>&1 &
